# Generated by Django 6.1.1 on 2026-09-11 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('institution', models.CharField(blank=True, help_text='e.g. University, School, or Organization', max_length=200)),
                ('phone_number', models.CharField(blank=True, help_text='e.g. +8801700000000', max_length=20)),
                ('occupation', models.CharField(blank=True, help_text='e.g. Student, Developer, Teacher', max_length=100)),
                ('learning_goal', models.CharField(blank=True, help_text='e.g. Master Full-Stack Django in 2026', max_length=255)),
                ('bio', models.TextField(blank=True, help_text='A short summary about yourself')),
                ('github_url', models.URLField(blank=True, help_text='GitHub or Portfolio link')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
