# Generated by Django 6.1.1 on 2026-09-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor_email',
            field=models.EmailField(blank=True, help_text='Email of the course instructor', max_length=254, null=True),
        ),
    ]
