"""
Django settings for todo_project project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
try:
    from dotenv import load_dotenv
except ImportError:  # python-dotenv is optional (env vars come from the host in production)
    def load_dotenv(*args, **kwargs):
        return False

try:
    import dj_database_url
except ImportError:
    dj_database_url = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file (override=True ensures live reload)
load_dotenv(BASE_DIR / '.env', override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-&3ar0er!%dulhbcudf1fp_hek4x*$0pn-d(^%-lgk1689w8+i(')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 't')

ALLOWED_HOSTS = [host.strip() for host in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if host.strip()]

# Render external hostname support
RENDER_EXTERNAL_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    CSRF_TRUSTED_ORIGINS = [f"https://{RENDER_EXTERNAL_HOSTNAME}"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'courses',
]

MIDDLEWARE = [
    'courses.middleware.IPBlockingMiddleware',  # 1. IP Blocking
    'django.middleware.security.SecurityMiddleware',
]

try:
    import whitenoise
    MIDDLEWARE.append('whitenoise.middleware.WhiteNoiseMiddleware')
except ImportError:
    pass

MIDDLEWARE.extend([
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Custom Application Middlewares
    'courses.middleware.RequestResponseLoggingMiddleware',  # 1. Request & Response Logging
    'courses.middleware.LanguageAndSessionManagementMiddleware',  # 2. Language & Session Management
    'courses.middleware.PerformanceTimingMiddleware',  # 3. Performance Timing
])


# Configurable Blocked IPs list (for IPBlockingMiddleware)
BLOCKED_IPS = [
    # Add IP strings to block, e.g.: '192.168.1.99'
]


ROOT_URLCONF = 'todo_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates' 
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'todo_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

if dj_database_url:
    default_db_url = f"postgresql://{os.getenv('DB_USER', 'postgres')}:{os.getenv('DB_PASSWORD', 'pranto121')}@{os.getenv('DB_HOST', 'localhost')}:{os.getenv('DB_PORT', '5432')}/{os.getenv('DB_NAME', 'todo_db')}"
    DATABASES = {
        'default': dj_database_url.config(
            default=os.getenv('DATABASE_URL', default_db_url),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'todo_db'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'pranto121'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }




# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'courses' / 'images',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Django 5.1+ removed STATICFILES_STORAGE; storages are configured via STORAGES.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}



# Email Configuration
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 't')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', f"AI Course Tracker <{EMAIL_HOST_USER}>" if EMAIL_HOST_USER else "AI Course Tracker <noreply@coursetracker.com>")

# Authentication URLs
LOGIN_URL = 'courses:signin'
LOGIN_REDIRECT_URL = 'courses:dashboard'
LOGOUT_REDIRECT_URL = 'courses:signin'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ==========================================
# DATABASE CACHING CONFIGURATION (DatabaseCache)
# ==========================================
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_cache_table',
        'TIMEOUT': 300,  # 5 minutes default cache timeout
        'OPTIONS': {
            'MAX_ENTRIES': 2000
        }
    }
}


# ==========================================
# SESSION STORAGE CONFIGURATION
# ==========================================
# 1. Session Storage Engine Options:
# - 'django.contrib.sessions.backends.db' (Default: Database backed)
# - 'django.contrib.sessions.backends.cache' (In-Memory Cache backed)
# - 'django.contrib.sessions.backends.cached_db' (Cache + Database persistent, recommended for speed & persistence)
# - 'django.contrib.sessions.backends.file' (File-system backed)
# - 'django.contrib.sessions.backends.signed_cookies' (Encrypted Cookie backed)

SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'

# 2. Session Cookie Expiration (14 days in seconds)
SESSION_COOKIE_AGE = 1209600  

# 3. Session Expiry on Browser Close (False = persistent, True = expires when browser closes)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  

# 4. Save Session on Every Request (Updates session expiration on each interaction)
SESSION_SAVE_EVERY_REQUEST = True  

# 5. Security Settings for Session Cookies
SESSION_COOKIE_HTTPONLY = True  # Prevents client-side JS access to session cookie
SESSION_COOKIE_NAME = 'sessionid'


# ==========================================
# AI ASSISTANT CONFIGURATION
# ==========================================
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '')


