"""
Django settings for todo_project project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&3ar0er!%dulhbcudf1fp_hek4x*$0pn-d(^%-lgk1689w8+i('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'courses',
]

MIDDLEWARE = [
    'courses.middleware.IPBlockingMiddleware',  # 1. IP Blocking
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Custom Application Middlewares
    'courses.middleware.GlobalAuthCheckMiddleware',  # 2. Global Authentication Check
    'courses.middleware.RequestResponseLoggingMiddleware',  # 3. Request & Response Logging
    'courses.middleware.LanguageAndSessionManagementMiddleware',  # 4. Language & Session Management
    'courses.middleware.PerformanceTimingMiddleware',  # 5. Performance Timing
]

# Configurable Blocked IPs list (for IPBlockingMiddleware)
BLOCKED_IPS = [
    # Add IP strings to block, e.g.: '192.168.1.99'
]


ROOT_URLCONF = 'todo_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates' 
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'todo_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'todo_db',
        'USER': 'postgres',
        'PASSWORD': 'pranto121',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'courses' / 'images',
]


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Authentication URLs
LOGIN_URL = 'courses:signin'
LOGIN_REDIRECT_URL = 'courses:dashboard'
LOGOUT_REDIRECT_URL = 'courses:signin'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ==========================================
# SESSION STORAGE CONFIGURATION
# ==========================================
# 1. Session Storage Engine Options:
# - 'django.contrib.sessions.backends.db' (Default: Database backed)
# - 'django.contrib.sessions.backends.cache' (In-Memory Cache backed)
# - 'django.contrib.sessions.backends.cached_db' (Cache + Database persistent, recommended for speed & persistence)
# - 'django.contrib.sessions.backends.file' (File-system backed)
# - 'django.contrib.sessions.backends.signed_cookies' (Encrypted Cookie backed)

SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# 2. Session Cookie Expiration (14 days in seconds)
SESSION_COOKIE_AGE = 1209600  

# 3. Session Expiry on Browser Close (False = persistent, True = expires when browser closes)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  

# 4. Save Session on Every Request (Updates session expiration on each interaction)
SESSION_SAVE_EVERY_REQUEST = True  

# 5. Security Settings for Session Cookies
SESSION_COOKIE_HTTPONLY = True  # Prevents client-side JS access to session cookie
SESSION_COOKIE_NAME = 'sessionid'


